# Generated by Django 5.2.3 on 2025-06-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='personal_photo',
            field=models.URLField(max_length=5000),
        ),
    ]
