# Generated by Django 5.2.1 on 2025-06-10 17:55

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='files', validators=[photos.validators.PhotoSizeValidator(5)]),
        ),
    ]
